#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


echo '🏗️👷 Styling, testing and building your project before committing'

yarn lint-staged
yarn run format || 
(
        echo '❌❌❌ Your styling looks disgusting. ❌❌❌
            Format failed. Run yarn run format, add changes and try commit again.';
        false;
)

# Check Prettier standards
yarn run check-format ||
(
    echo '🤢🤮🤢🤮 Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run yarn run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
yarn run check-lint ||
(
        echo '😤🏀👋😤 Get that weak shit out of here! 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
yarn run check-types ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'